### ISSUE TITLE
consider getting a new maintainer

### ISSUE THREAD

**Issue by xjamundx** [jaredhanson/deamdify#20]
Are you willing to let someone else assist in maintaining deAMDify? There are a lot of unmerged PRs and comments without feedback. Let us know how we can help!

**Comment by TheAlphaNerd** [comment]
+1 on this I would be willing to step forward to help with this

**Comment by yoshuawuyts** [comment]
@TheAlphaNerd we're considering picking this up at the office, also interested in helping out.

**Comment by xjamundx** [comment]
I've emailed @jaredhanson and have not heard back as well. A fork may be in order :-/

**Comment by TheAlphaNerd** [comment]
I just emailed him as well.

**Comment by reggi** [comment]
:+1:  What's the best way to move forward with a fork? @xjamundx @TheAlphaNerd?

**Comment by xjamundx** [comment]
Steps:

1. Come up with a new name
2. Start a new repo
3. Add a ton of contributors (because seriously)
4. Publish to NPM

**Comment by xjamundx** [comment]
As far as a new name here are 5 suggestions:

- `browserify-amd`
- `deamdify2`
- `amd2cjsify`
- `amd2cjs`
- `unamdify`

**Comment by TheAlphaNerd** [comment]
+1 for deamdify2.  That way if we ever get a response we can deprecate, rollback, and make minimal changes / an alias.

**Comment by yoshuawuyts** [comment]
deamdify2 sounds good. Maybe an additional point 6 is to review and merge all PRs on deamdify. Also I've got my Sunday evening (UTC+1) blocked out to hack on this.

**Comment by yoshuawuyts** [comment]
Didn't come around to this on Sunday. Next few months I'll be too busy to spearhead a fork. If someone else can take the lead I'd be happy to drop in a few patches.

**Comment by xjamundx** [comment]
I'll do something today!

**Comment by xjamundx** [comment]
- Created https://github.com/5to6/deamdify2/
- Published `deamdify2@0.2.0`
- Added a few of you as maintainers on the github repo. 

I don't actually want to be the maintainer if possible :-p

**Comment by yoshuawuyts** [comment]
dope! :D

**Comment by tbranyen** [comment]
@xjamundx I'd like to assist maintaining if you could add me to that project.  My primary goal is to simply support AMD plugins.

**Comment by xjamundx** [comment]
@tbranyen will totally add you. i think at this point. we're not doing much with it (I moved to webpack don't tell anyone), but if there's any real interest I'm happy to help make things happen!

**Comment by tbranyen** [comment]
@xjamundx okay, I noticed the master branch is failing, left a comment here: https://github.com/5to6/deamdify2/issues/1

If the case is that you aren't interested in this anymore, please make me an owner and I'll take over and fix the tests and get it on travis, etc...

**Comment by tbranyen** [comment]
Also NPM owner if you don't mind so I can publish updates.

**Comment by tbranyen** [comment]
Done & done.  I'm the new maintainer as of now.  Please reference me in any PRs.  I'll also be answering any questions in: https://gitter.im/jaredhanson/deamdify
