### ISSUE TITLE
support dependencies declared with expressions

### ISSUE THREAD

**Issue by phillipgreenii** [jaredhanson/deamdify#29]
In some usages of dojo, the modules are cleverly defined by specifying a string and splitting on it: 

    define('my module', 'dep1 dep2 dep3'.split(' '), function(dep1, dep2, dep3) {
      //i'm clever
    });

This scenario isn't caught by deamdify, but it could be

**Comment by tbranyen** [comment]
Should it be?  Dynamic construction of modules should not be supported IMO.  I suppose it doesn't hurt if we can just migration that section of code and retain functionality, but seems like a slippery slope.  

For instance I would not want deamdify to fix:

``` 
var dynamicRequire = require;

require('../this/should/be/inlined');

for (var i = 0; i < someListOfModules; i++) {
  dynamicRequire(someListOfModules[i]);
}
```

**Comment by phillipgreenii** [comment]
I agree, support for renaming require is beyond this project.  I also agree that it is questionable to support things like `'dep1 dep2 dep3'.split(' ')`.  However, my motiviation for using deamdify is to make it work with the Esri Javascript API and it uses that pattern.  (this is how I discovered the problem)

**Comment by tbranyen** [comment]
Ah of course, damn you ESRI.  I suppose handling that case may fix other poorly formed modules as well.
