### ISSUE TITLE
Support for UMD

### ISSUE THREAD

**Issue by jzaefferer** [jaredhanson/deamdify#33]
I tried building jQuery UI, which uses UMD without CJS, with browserify and this module. While its likely that I've missed something, it doesn't seem to work, and the "// TODO: Implement support for amdWeb UMD modules." comment implies that it can't work. 

My test is here: https://github.com/jzaefferer/browserify-jquery-ui

Running `npm run build` will build a bundle, but it doesn't make a difference if deamdify is used or not, it won't do anything.

What it should be doing is to find the `if ( typeof define === "function" && define.amd ) {` check and resolve the `define` call inside of that.

**Comment by tbranyen** [comment]
We merged https://github.com/jaredhanson/deamdify/commit/283a1607f578d6dd9d20b1b6a5dcf4970ba2318f which claims to add it

**Comment by jzaefferer** [comment]
No release since April? Okay.

I installed via `npm install jaredhanson/deamdify#master` and ran my build script again, nothing changed.  Eventually I found that there are two ways to apply transforms, `-t` only applies to "local" modules, `-g` applies to everything. With that, the `autocomplete.js` dependency is actually modified, which looks alright. Unfortunately it fails to include the jQuery dependency, instead it replaces it with this:
```js
},{}],3:[function(require,module,exports){
module.exports = function () {
    return jQuery;
}();
},{}]},{},[1]);
```
Any ideas?

**Comment by StreetStrider** [comment]
I have the very same issue.
jQuery UI for some reason dropped support for CJS in 1.11. So I've recalled deamdify.
jQ UI module has the following structure:
```js
(function( factory ) {
        if ( typeof define === "function" && define.amd ) {

                // AMD. Register as an anonymous module.
                define([
                        "jquery",
                        "./core",
                        "./widget"
                ], factory );
        } else {

                // Browser globals
                factory( jQuery );
        }
}(function( $ ) {

return $.widget( "ui.tabs", {
        version: "1.11.4",
// …
```
So it is an AMD module with fallback to global (`factory(jQuery)`) with NO CJS (so it is not actually an full-UMD). It also has internal deps (`'./widget'`) and external (`'jquery'`).
deamdify transformation does not really do anything special with it, so this module works as «global-module».
I expect deamdify to pass `define` into such module and both internal and external deps work ok. Not happening. For now I'm using `browserify-shim` which treat jQ UI as global-ish and force me to manually resolve jQ UI dependencies, which is makin me sad.

**Comment by au-phiware** [comment]
[jquery/sizzle](https://github.com/jquery/sizzle) has the same problem. I.e. (1) the call to define is guarded by the existence of define (that 283a160 does appear to overcome); and (2) the function passed to define relies on a variable from its enclosing closure, this means that deamdify only output [line 2233 of sizzle.js](https://github.com/jquery/sizzle/blob/0e20ac65796ea7dbe780789b01a4870d31b8ecb4/src/sizzle.js#L2233). This seems like a major flaw.

**Comment by au-phiware** [comment]
I have created a sample project that uses my changes: https://github.com/au-phiware/deamdify-sample/

**Comment by tbrandvik** [comment]
Just a quick user note in case somebody finds it useful: I have found that if I use the au-phiware deamdify module and add 

"browserify": {
    "transform": "deamdify"
},

to jquery-ui/package.json

then all the jquery-ui files are transformed correctly. Using "browserify -g deamdify ..." from the command-line didn't work for me as some of the third-party modules I use don't work with deamdify.

Thanks for fixing the deamdify bug and putting it up!

**Comment by au-phiware** [comment]
@tbrandvik, which third-party modules that you use don't work with deamdify?

**Comment by ishaikovsky** [comment]
Last released version of underscore - is not getting correctly transformed for me as well using current deamdify code.
