### ISSUE TITLE
Ordering with template transforms like hbsfy are important

### ISSUE THREAD

**Issue by cayleyh** [jaredhanson/deamdify#7]
Using both https://github.com/epeli/node-hbsfy and deamdify, hbsfy has to be included first as a transformation else deamdify will error on the loaded hbs file with the error "Fatal error: Line 1: Unexpected token <", which is pretty unhelpful when debugging.

Not sure if this is a case that you actually want to try and handle, or just treat as a known issue. This could also be a problem with other template transforms for browserify.

**Comment by tbranyen** [comment]
This was because the transform did not detect if it was operating on JavaScript or some random arbitrary file like Handlebars.  Therefore I've updated the codebase here: 008fa7fcf003434b93f8f6dfdcb9276a9713c456 to only affect JavaScript.
